mybatis:
  mapper-locations:
  - classpath*:/mapping/**/*.xml
server:
  port: 8210
datasource:
  password: HaoHao11
  username: tml
  url: jdbc:mysql://47.99.59.53/finance?useUnicode=true&characterEncoding=utf-8
  driverClass: com.mysql.jdbc.Driver
  initialSize: 1
  minIdle: 1
  maxActive: 20
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: select 1
  validationQueryTimeout: 60000